### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by hiddensea** [xSetrox/iRightClick#1]
when I try to install, I get this error.

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

So I use the file location and get this error:

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\lance\\discord.py-self'

so i delete discord.py and try again. I get this error

 ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

You might aswell just make this into a .bat as those are way easier to install and run.

**Comment by xSetrox** [comment]
I screwed up and mixed up pip freeze with pipreqs. Most of those requirements you won't need. I'll be pushing a commit soon that replaces it with the right file.
As for installation, either download git and clone the entire repo or download the .zip and then cd into it to install the requirements with pip.

**Comment by xSetrox** [comment]
This has been fixed.
