### ISSUE TITLE
You must enter a collection slug/ID.

### ISSUE THREAD

**Issue by YEsmaR1** [xSetrox/iRightClick#8]
when i do 'main.py boredapeyachtclub'  it says " You must enter a collection slug/ID."

**Comment by shishtaouk09** [comment]
did u found a fix ?

**Comment by xSetrox** [comment]
Can you try running it with `python3 main.py boredapeyachtclub`? Or `python2` as a replacement, or `py`, whatever you run python with.

**Comment by xSetrox** [comment]
Closing as duplicate of #6
