### ISSUE TITLE
Client Response Error

### ISSUE THREAD

**Issue by dangermouse5** [xSetrox/iRightClick#9]
Ran this command: python3 main.py boredapeyachtclub

Received this error:

File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api.opensea.io/api/v1/assets?order_direction=desc&collection=boredapeyachtclub&limit=50&offset=0')

**Comment by xSetrox** [comment]
Looks like you got blocked, lol. Turn on a VPN or proxy.

**Comment by xSetrox** [comment]
Actually I'm getting this same issue too. Perhaps they changed some things. I'm looking into this.

**Comment by xSetrox** [comment]
Sorry for a third comment; looks like Cloudflare is blocking you. Happening to me too. Turn off your VPN; any block you get for "spamming" the API is both rare (can be made rarer by adjusting the delay) and temporary.
